baseURL = "/"
languageCode = "en-us"
title = "ftwproductions.com"
theme = "blade-hugo"
# googleAnalytics = ????

############################### markup  #################################
[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.parser]
      attribute = true
      autoHeadingID = true
      autoHeadingIDType = "github"
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true
      xhtml = false

############################### parameters  #################################
[params]
	description = "My site description"
    author = "Ryan Dailey"
    authorImage = "/images/.jpg"
	featured_image = "/images/2020/06/skm-banner-1920x703.png"

############################### parameters  #################################
[taxonomies]
  category = "categories"
  show = "shows"
  tag = "tags"

#these are standard main menu items for the navbar
[[menu.main]]
  name = "HOME"
  url = "/"
  weight = 1
  
[[menu.main]]
  name = "ABOUT"
  url = "/about"
  weight = 2
  
[[menu.main]]
  name = "NEWS"
  url = "/news"
  weight = 3

#[[menu.main]]
#  name = "Blog"
#  url = "/blog"
#  weight = 4

#these are the dropdown menus with children based on pages in that section
[[menu.maindrop]]
  identifier = "advertising"
  name = "ads"
  url = "/advertising"
  weight = 1

[[menu.maindrop]]
  identifier = "contact"
  name = "contact us"
  url = "/contact"
  weight = 2

#these are dropdown menus with children based on taxonomy tag
[[menu.maindroptax]]
  identifier = "past-productions"
  name = "past productions"
  url = "/past-productions"
  weight = 3
  
#these are standard black icons for social media  
[[menu.social]]
    name = "Twitter"
    url = "https://twitter.com/ForTheWhim"
    pre = "<i class='fab fa-twitter'></i>"
	weight = 1

[[menu.social]]
    name = "Facebook"
    url = "https://www.facebook.com/ForTheWhim"
    pre = "<i class='fab fa-facebook-f'></i>"
	weight = 2

[[menu.social]]
    name = "Instagram"
    url = "https://www.instagram.com/forthewhim/"
    pre = "<i class='fab fa-instagram'></i>"
	weight = 3
	
#these are inverted color icons for social media#
[[menu.socialinv]]
    name = "Twitter"
    url = "https://twitter.com/ForTheWhim"
    pre = "<i class='fab fa-twitter fa-inverse'></i>"
	weight = 1

[[menu.socialinv]]
    name = "Facebook"
    url = "https://www.facebook.com/ForTheWhim"
    pre = "<i class='fab fa-facebook-f fa-inverse'></i>"
	weight = 2

[[menu.socialinv]]
    name = "Instagram"
    url = "https://www.instagram.com/forthewhim/"
    pre = "<i class='fab fa-instagram fa-inverse'></i>"
	weight = 3
	
[[menu.footer]]
  name = "About"
  url = "/about"

[[menu.footer]]
  name = "Privacy"
  url = "/privacy"
